<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="1" hostname="DESKTOP-R8LNRUV" name="testCases.TestCase_Scenario_0001_02" tests="2" failures="1" timestamp="2022-10-21T09:34:58 SGT" time="148.381" errors="0">
  <testcase name="test_CIMBDeals_scn0001_02" time="62.020" classname="testCases.TestCase_Scenario_0001_02">
    <failure type="java.lang.AssertionError" message="test_CIMBDeals_scn0001_02 : Intentionally failed assertion to check snapshot captured in report expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: test_CIMBDeals_scn0001_02 : Intentionally failed assertion to check snapshot captured in report expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:751)
at testCases.TestCase_Scenario_0001_02.test_CIMBDeals_scn0001_02(TestCase_Scenario_0001_02.java:41)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:213)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- test_CIMBDeals_scn0001_02 -->
  <system-out/>
  <testcase name="test_CIMBDeals_scn0001_02" time="86.361" classname="testCases.TestCase_Scenario_0001_02">
    <skipped/>
  </testcase> <!-- test_CIMBDeals_scn0001_02 -->
  <system-out/>
</testsuite> <!-- testCases.TestCase_Scenario_0001_02 -->
